development:
  adapter: async
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: grp_message_app_production

test:
  adapter: async

production:
  adapter: async
#  url: <%#= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: grp_message_app_production
